- name: play level variables
  hosts: local
  connection: local
  vars_files:
  - variables.yml
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "My name is {{ NAME }}, Working as a {{ PROFESSION }} and i have {{ EXPERIENCE }} of experience"   